export interface JugadorField {
    [key: string]: string | boolean | string[] | number;
    name: string,
    type: string,
    viewName: string,
    required: boolean,
    contenido: string[],
    sugerencia: string,
    group: string[],
    minVal: number,
    maxVal: number,
    minLen: number,
    maxLen: number,
    esKey: boolean,
    esNumeroPequenio: boolean,
    esNumeroMediano: boolean,
    esNombre: boolean,
    esAlfanumerico: boolean,
    esUrl: boolean,
    esCadena: boolean,
    esUnico: boolean,
    esMultiple: boolean,
    esMoneda: boolean,
    esRangoCategorias: boolean,
    esGlobalSkill: boolean,
    esSpecifSkill: boolean,
    esSkill: boolean,
    esPower: boolean,
    esMovement: boolean,
    esAttackSkill: boolean
    esDefendSkill: boolean,
    esGoalKeepingSkill: boolean,
    esMentalitySkill: boolean
    esJuego: boolean,
    esGeneral: boolean,
    esPersonal: boolean
}