export interface JugadorField {
    name: string,
    type: string,
    viewName: string,
    required: boolean,
    contenido: [],
    sugerencia: string,
    group: [],
    minVal: number,
    maxVal: number,
    minLen: number,
    maxLen: number,
    esNumero_pequenio: boolean,
    esNumero_mediano: boolean,
    esNombre: boolean,
    esCadena: boolean,
    esUnico: boolean,
    esMultiple: boolean,
    esMoneda: boolean,
    esRango_categorias: boolean,
    esSkill: boolean,
    esGlobalSkill: boolean,
    esSpecifSkill: boolean,
    esAttackSkill: boolean
    esDefendSkill: boolean,
    esGoalKeepingSkill: boolean,
    esMentalitySkill: boolean
}